name: 'Deploy Google App Engine Project'
description: 'Deploy Google App Engine Project'
author: 'Xiang Zheng'
inputs:
  service_account_email:
    description: 'GCP auth email'
    required: true

  service_account_key:
    description: 'GCP secret key'
    required: true

  proejct_id:
    description: 'GAE project id'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GCP_SA_EMAIL }}
    - ${{ inputs.GCP_SA_KEY }}
    - ${{ inputs.PROJECT_ID }}

branding:
  icon: 'award'
  color: 'blue'