name: 'Deploy Google App Engine Project'
description: 'Deploy Google App Engine Project'
author: 'Xiang Zheng'
inputs:
  service_account_email:
    description: 'The service account email which will be used for authentication.'
    required: true

  service_account_key:
    description: 'The service account key which will be used for authentication.'
    required: true

  project_id:
    description: 'GAE project id'
    required: true

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'award'
  color: 'blue'