name: 'Deploy Google App Engine Project'
description: 'Deploy Google App Engine Project'
author: 'Xiang Zheng'
inputs:
  service_account_email:
    description: 'GCP auth email'
    required: true

  service_account_key:
    description: 'GCP secret key'
    required: true

  project_id:
    description: 'GAE project id'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service_account_email }}
    - ${{ inputs.service_account_key }}
    - ${{ inputs.project_id }}

branding:
  icon: 'award'
  color: 'blue'