on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushlish project to Google App Engine
    steps:
    - name: Hello world action step
      uses: zxyle/pushlish-gae-action@master

    - name: Get gcloud version
      run: gcloud version