name: Test Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gcloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        proejct_id: ${{ secrets.PROJECT_ID }}

    - name: Print gcloud SDK version
      run: gcloud info
