name: Test Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gcloud SDK
      uses: zxyle/publish-gae-action@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Print gcloud SDK version
      run: gcloud info

    - name: Print gcloud SDK version
      run: gcloud info

    - name: Deploy to GAE
      run: |
        gcloud config set project ${{ secrets.PROJECT_ID }}
        gcloud -q app deploy app.yaml --promote
        gcloud -q app deploy cron.yaml
