name: Test Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gcloud SDK
      uses: zxyle/publish-gae-action@master

    - name: Print gcloud SDK version
      run: gcloud version
